global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - send_resolved: true
    to: 'YOUR_EMAIL@gmail.com'
    from: 'YOUR_EMAIL@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'YOUR_EMAIL@gmail.com'
    auth_identity: 'YOUR_EMAIL@gmail.com'
    auth_password: 'YOUR_APP_PASSWORD'